---
title: "InteractiveParksMap"
author: "Luke Zaruba"
date: "Updated 3/20/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# Loading Libraries
library(sf)
library(leaflet)

# Loading Spatial Dataset
shape <- read_sf(dsn = "E:\\BA - Gustavus\\ParkAccessibility", layer = "WGS_Parks")

# Creating Map
bins <- c(0,100,200,300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500,1600)
pal <- colorBin("viridis", domain = shape$Avg_NwkDis, bins = bins)

labels <- sprintf(
  "<strong>%s</strong><br/>%g meters",
  shape$GEOID10, shape$Avg_NwkDis
) %>% lapply(htmltools::HTML)

m <- leaflet(shape) %>%
  setView(-93.2649, 44.9642, 11) %>%
  addProviderTiles(providers$Stamen.Toner) %>%
  addPolygons(
    fillColor = ~pal(Avg_NwkDis),
    weight = 0,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 1,
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8 px"),
      textsize = "15px",
      direction = "auto")) %>%
  addLegend(pal = pal, values = ~Avg_NwkDis, title = "Avg. Network Distance", opacity = 0.9, position = "bottomright")
```

```{r, echo=FALSE}
m
```

